<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>Library</OutputType>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendPlatformToOutputPath>false</AppendPlatformToOutputPath>
    <AssemblyName>MepPanel.Blocks.AutoCAD</AssemblyName>
    <RootNamespace>MepPanel.Blocks.AutoCAD</RootNamespace>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <AutoCadDir Condition="'$(AutoCadDir)' == ''">C:\Program Files\Autodesk\AutoCAD 2021</AutoCadDir>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AutoCadAssemblyInfo.cs" />
    <Compile Remove="Properties\AssemblyInfo.cs" />
    <Compile Remove="MepDrawingToolPanel.cs" />
    <None Include="AutoCadAssemblyInfo.cs.exclude" Condition="Exists('AutoCadAssemblyInfo.cs.exclude')" />
    <None Include="Properties\AssemblyInfo.cs.exclude" Condition="Exists('Properties\AssemblyInfo.cs.exclude')" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AcCoreMgd">
      <HintPath>$(AutoCadDir)\AcCoreMgd.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="AcDbMgd">
      <HintPath>$(AutoCadDir)\AcDbMgd.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="AcMgd">
      <HintPath>$(AutoCadDir)\AcMgd.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="AdWindows">
      <HintPath>$(AutoCadDir)\AdWindows.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <ProjectReference Include="..\MepPanel.Core\MepPanel.Core.csproj" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
</Project>
